version: '3'

volumes:
  easy_notify_postgres_data:
  easy_notify_redis_data:

services:
  postgres:
    container_name: posrgres
    image: postgres:10.2
    restart: always
    ports:
      - 5432:5432/tcp
    environment:
        - POSTGRES_USER=test_user
        - POSTGRES_PASSWORD=test_user
        - POSTGRES_DB=easy_notify
    volumes:
      - easy_notify_postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    command: >
      --requirepass root
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - easy_notify_redis_data:/data
