version: 2
jobs:
  install_dependencies:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/easy-notify

  build:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build client
          command: yarn run build

  lint:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint client
          command: yarn run lint

  test:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3-browsers
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test client
          command: yarn run test --code-coverage

  test_e2e:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3-browsers
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test client (E2E)
          command: yarn run e2e

  deploy:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Heroku auth
          command: ./scripts/heroku_key_setup
      - add_ssh_keys:
          fingerprints:
            - "e2:1c:63:90:01:61:54:ae:13:49:48:2b:b9:fd:b8:6c"
      - run:
          name: Deploy application
          command: ./scripts/heroku_deploy easy-notify

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - test_e2e:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build
            - test
            - test_e2e
          filters:
            branches:
              only: master
