version: 2
jobs:
  install_dependencies:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/easy-notify

  build_client:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build server
          command: yarn run build-client

  lint_client:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint client
          command: yarn run lint-client

  test_client:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3-browsers
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test client
          command: yarn run test-client --code-coverage

  test_client_e2e:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3-browsers
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test client (E2E)
          command: yarn run e2e

  build_server:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build server
          command: yarn run build-server

  lint_server:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint server
          command: yarn run lint-server

  test_server:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3
      - image: redis:2.8.7
      - image: postgres:10.2
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test server
          command: yarn run test-server

  deploy:
    working_directory: ~/easy-notify
    docker:
      - image: circleci/node:9.3
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy application
          command: echo "No deploy configured yes"

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - build_client:
          requires:
            - install_dependencies
      - build_server:
          requires:
            - install_dependencies
      - lint_client:
          requires:
            - install_dependencies
      - lint_server:
          requires:
            - install_dependencies
      - test_client:
          requires:
            - install_dependencies
      - test_client_e2e:
          requires:
            - install_dependencies
      - test_server:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build_client
            - build_server
            - test_server
            - test_client
          filters:
            branches:
              only: master
