#!/bin/bash
wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh

cat > ~/.netrc << EOF
machine api.heroku.com
  login $HEROKU_LOGIN
  password $HEROKU_API_KEY
EOF

mkdir ~/.ssh/ && echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
