#!/bin/sh -e
APP_NAME=$1

git remote add heroku git@heroku.com:$APP_NAME.git
git fetch heroku

PREV_WORKERS=$(heroku ps --app $APP_NAME | grep "^worker." | wc -l | tr -d ' ')

DEPLOY_START=`date +%s`

echo "Push changes to heroku."
# deploy code changes (and implicitly restart the app and any running workers)
git push heroku $CIRCLE_SHA1:refs/heads/master

echo "Disable maintenance mode."
heroku maintenance:off --app $APP_NAME

DEPLOY_END=`date +%s`
ELAPSED=$(( $DEPLOY_END - $DEPLOY_START ))

echo "  $ELAPSED seconds, without maintenance mode."]

echo "Deploy completed!"
